= SEMIC Core Vocabularies Handbook
:description: SEMIC Core Vocabularies Handbook
:sectanchors:
:url-repo: https://github.com/SEMICeu/core-vocs-handbook


This Handbook provides a clear and straightforward guide on how to use SEMIC Core Vocabularies (CV). It is intended for business users who wish to understand how the Core Vocabularies can be useful, and for semantic engineers who seek straightforward guidance for specific use cases.

This handbook is organised in two parts.  The first part is explanatory while the second part offers hands-on instructions.

For first-time readers of this Handbook, starting with the first part is recommended xref:introduction.adoc[introduces interoperability], where interoperability is introduced and the role Core Vocabularies is explained, together with important xref:use-cases.adoc[use cases] and a xref:conceptual-framework.adoc[conceptual framework] for understanding the semantic data specifications.


Readers familiar with the SEMIC Core Vocabularies and seeking practical guidance are advised to go directly to the second part of the Handbook. It describes approaches and methodology recommendations for:

* xref:how-to-create-new-data-models.adoc[creating new semantic data specifications or stand-alone data models] (re-)using Core Vocabularies, and
* xref:how-to-map-existing-data-models.adoc[mapping existing data models] to the Core Vocabularies.

The Core Vocabularies Handbook does NOT cover the following:

* a complete methodology for syntax binding and toolset for creating data model specifications, as the Core Vocabularies intend to remain syntax neutral.
* data model library, or tools. Such choices are heavily dependent on the domain and the task at hand.
