= SEMIC Core Vocabularies Handbook
:description: SEMIC Core Vocabularies Handbook
:sectanchors:
:url-repo: https://github.com/SEMICeu/core-vocs-handbook


This Handbook provides a clear and straightforward guide on how to use SEMIC Core Vocabularies (CV). It supersedes the first version,  https://interoperable-europe.ec.europa.eu/sites/default/files/inline-files/ISA%20Handbook%20for%20using%20Core%20Vocabularies.pdf[e-Government Core
Vocabularies handbook: Using horizontal data standards for promoting interoperability]. Key updates include more detailed guidelines and examples in the form of extended tutorials to assist practical use of the Core Vocabularies, as well as including more recent popular languages, such as JSON-LD.

In addition, the handbook is now explicitly intended both for business users who wish to understand how the Core Vocabularies can be useful, and for semantic engineers who seek straightforward guidance for specific use cases.

This handbook is organised in four chapters. Chapter 1 is aimed at first-time readers, Providing an xref:introduction.adoc[introduction], and where xref:introduction.adoc#sec:interoperability[interoperability], the role of xref:introduction.adoc#sec:Core_Vocabulary[Core Vocabularies], and important xref:introduction.adoc#sec:use-cases[use cases] are described briefly.

Chapters 2 and 3 serve a mixed audience, containing use cases, guidelines, and hands-on tutorials. The chapters address two principal cases:

* xref:how-to-create-new-data-models.adoc[creating new semantic data specifications or stand-alone data models] (re-)using Core Vocabularies, and
* xref:how-to-map-existing-data-models.adoc[mapping existing data models] to the Core Vocabularies.

Chapter 4 contains xref:Concluding-remarks.adoc[concluding remarks] and looks ahead toward possible future considerations or extensions.

Further information about SEMIC can be found at the https://interoperable-europe.ec.europa.eu/collection/semic-support-centre[SEMIC Support Centre] and its related https://github.com/SEMICeu[repositories on GitHub].
