
= Core Vocabularies Handbook
[[sec:intro-to-interoperability]]

This Handbook aims to explain the role of Core Vocabularies in enabling semantic interoperability at the EU level and to practically guide public administrations in using Core Vocabularies to achieve this goal. This section introduces what interoperability is, what makes it semantic, and how Core Vocabularies contribute to it.

== Introduction to interoperability

Sharing data easily is indispensable for effective and efficient public services. Sharing may be through offering one point of access, and often involves reusing the data in multiple applications across multiple departments and organisations. To make this work, the systems need to be interoperable.  

=== What is interoperability

Following the https://ec.europa.eu/isa2/sites/default/files/eif_brochure_final.pdf[European Interoperability Framework (EIF)], interoperability is defined as “the ability of organisations to interact towards mutually beneficial goals, involving the sharing of information and knowledge between these organisations, through the business processes they support, by means of the exchange of data between their ICT systems”, where, for the purpose of EIF ‘organisations’ refers to “public administration units or any entity acting on their behalf, or EU institutions or bodies”. It is what “enables administrations to cooperate and make public services function across borders, across sectors and across organisational boundaries.”, including enabling “public sector actors to connect, cooperate and exchange data while safeguarding sovereignty and subsidiarity”, as described in https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52022DC0710[EUR-Lex - 52022DC0710 - EN - EUR-Lex].


=== Why is interoperability needed? 

The requirement for interoperability has been identified at the EC level and consequently different actions and regulations are established to facilitate and support interoperability (summarised in the next section). They stress that data must be shared with a shared understanding [EIF] such that the meaning of the data is preserved over time, when it is shared between co-legislators and across agencies in whole or in part, when it is transferred between systems of different agencies, and when it is used in the various information systems implemented with distinct technologies.

In the context of public sector interoperability specifically, it functions as an enabler of a number of benefits. Among others, the EC has identified in EUR-Lex - 52022DC0710 - EN - EUR-Lex that it 

* will contribute to GDP growth and will be a cost-saver: an "estimated increase of 0.4% in EU GDP" and saving individuals "up to 24 million hours a year, or EUR 543 million", whereas "[b]usinesses could save 30 billion hours or EUR 568 billion a year." (referenced https://publications.jrc.ec.europa.eu/repository/handle/JRC127330[source])
* will contribute positively to public values, as it already has done for multilingualism and inclusive public services. 
and it is "to ensure the proper functioning of the internal market" both within and between sectors https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R0868[Data governance act].

Mechanisms that foster interoperability contribute to improving individuals’ and businesses’ access to data to encourage data-driven innovation and a more integrated and efficient data economy. A prerequisite for this is that the data must have a clearly specified meaning so that it will be used correctly by all users sharing the same understanding about that data. This, in turn, also contributes to clear data provenance and correctness for the data stored and used, which is important for increasing trust and data availability.  These capabilities could further contribute to consistent interpretation and foster reliable data sharing and access across multiple sectors and administrative levels, which may also contribute to policymaking and implementation.

=== Existing acts and frameworks 

The European Union has formulated Acts, regulations, and frameworks that intend to foster achieving that, including the https://digital-strategy.ec.europa.eu/en/policies/data-act[Data Act], the https://digital-strategy.ec.europa.eu/en/policies/data-governance-act[Data Governance Act], the https://ec.europa.eu/isa2/sites/default/files/eif_brochure_final.pdf[European Interoperability Framework (EIF)], and the https://interoperable-europe.ec.europa.eu/interoperable-europe/interoperable-europe-act[Interoperable Europe Act], which underscore the importance of harmonised data practices across member states. These Acts and frameworks emphasise that true interoperability goes far beyond just connecting systems at a technical level. 

The EU Data Act is a *legislative framework* aimed at enhancing the EU's data economy by improving access to data for individuals and businesses. It entered into force on January 11, 2024, and is designed to ensure fairness in data allocation and encourage data-driven innovation.  

The Data Governance Act (DGA) is a *regulation by the European Union* aimed at facilitating data sharing and increasing trust in data usage. It establishes a framework for the reuse of publicly held data and encourages the sharing of data for altruistic purposes, while also regulating data intermediaries to enhance data availability and overcome technical barriers. The act is part of the broader European strategy for data, which seeks to create a more integrated and efficient data economy.

The EIF provides specific guidance on *how to set up interoperable digital public services*.  It gives guidance, through a set of recommendations, to public administrations on how to improve governance of their interoperability activities, establish cross-organisational relationships, streamline processes supporting end-to-end digital services, and ensure that existing and new legislation do not compromise interoperability efforts. 

The Interoperable Europe Act, which entered into force on 11 April 2024, aims to enhance cross-border interoperability and cooperation in the public sector across the EU. It is designed to support the objectives of the Digital Decade, ensuring that 100% of key public services are available online by 2030, including those requiring cross-border data exchange. The Act addresses challenges by creating tools for interoperability within public administrations and removing legal, organizational, and technical obstacles. It envisions an emerging ‘network of networks’ of largely sovereign actors at all levels of government, each with their own legal framework and mandates, yet all interconnected”, i.e., for seamless cross-border cooperation, which is to be supported by mandatory assessments. +

To achieve interoperability, one has to  elucidate its multiple interacting sub-components. This could be along the line of the high-level conceptual model of the https://interoperable-europe.ec.europa.eu/collection/nifo-national-interoperability-framework-observatory/european-interoperability-framework-detail[EIF], which intersects with national interoperability frameworks and domain-specific interoperability frameworks such as the https://knowledge-base.inspire.ec.europa.eu/index_en[INSPIRE Directive].
In the https://interoperable-europe.ec.europa.eu/collection/nifo-national-interoperability-framework-observatory/solution/eif-toolbox/6-interoperability-layers[EIF toolbox], each higher layer rests upon an interoperable lower layer of infrastructure; e.g., organisational interoperability requires semantic operability such that information can be exchanged seamlessly, which, in turn, requires IT infrastructure interoperability.  +

They also can be viewed as layers of local, provincial, national, and EU-wide levels of interoperability to accommodate a plethora of e-Government information exchange scenarios or smart cities and communities specifically https://living-in.eu/sites/default/files/files/proposal-for-a-european-interoperability-framework-no0821160enn.pdf[EIF4SCC]. Alternatively, an interoperability framework can be envisioned as foundations upon which government services are built https://www.sita.co.za/sites/default/files/documents/MIOS/Signed%20-%20MIOS%20V6.0%20Framework.pdf[MIOS], or as one of the constituent pillars that enable goals such as citizen convenience, increased productivity, and lower costs of government operations.  +

In sum, there are two key reasons to seek interoperability in public administrations:

. *Instrumental Value* – Standardised data and information exchange simplifies cross-border operations, enabling organisations to:
** comply with regulations more easily; 
** contribute to reducing overhead costs by automating processes and paperwork across ministries that would have to be carried out only once; 
** streamline administrative tasks and data accuracy, preventing misinterpretation of data through standardised data exchange; 
** improve service delivery.
. *Legal Requirements* – EU regulations  and policy frameworks such as the _Data Act_, _Data Governance Act_, and the _Interoperable Europe Act_ for structured and secure data exchange. Compliance ensures smoother interactions with public authorities.

== What is semantic interoperability and how to achieve it 

While data exchange is an evident requirement for interoperability, there are fine but crucial distinctions between data format, syntactic, and semantic interoperability. A standardised syntax and data format to store data lets one exchange data, such as creating an SQL database dump in one tool and seamlessly reopening it in another, or lets one send and receive emails that arrive properly in each other’s inbox.  +

Interoperability at the semantic level concerns the meaning of that data. One may have a format and language to represent data, such as XML, but with a tag <bank> … </bank>, neither the software nor the humans can determine from just that what sort of bank is enclosed within the tags. Such meaning is defined in artefacts including vocabularies, thesauri, and ontologies. A “<fin:bank>” tag in a document is then an implemented version of its definition at the semantic layer, where it has a definition and a number of properties specified, like that the fin:bank is a type of organisation with a board of directors and a location for its headquarters. This enables not only correct sending and receiving of data, but also exchanging data reliably, accessing the right data when querying for information and obtaining relevant data in the query answer, and merging data.   +

According to the https://eur-lex.europa.eu/resource.html?uri=cellar:2c2f2554-0faf-11e7-8a35-01aa75ed71a1.0017.02/DOC_3&format=PDF[Revised EIF, section 3.5], semantic interoperability "ensures that the precise format and meaning of exchanged data and information is preserved and understood throughout exchanges between parties, in other words ‘what is sent is what is understood’." Besides aforementioned syntactic interoperability, it has the semantic component as well, which "refers to the meaning of data elements and the relationship between them." and "includes developing vocabularies and schemata to describe data exchanges". One recommended way to achieve semantic interoperability between public administrations  is to use  https://semiceu.github.io/style-guide/1.0.0/terminological-clarifications.html#sec:what-is-a-cv-specification:~:text=types%20of%20assets.-,What%20is%20a%20Core%20Vocabulary%20(CV)%20specification%3F,-Definition%0AA%20Core[*Core Vocabularies]*, which is where the terms are specified and disambiguated. 


== What is a Core Vocabulary?

A Core Vocabulary (CV) is a basic, reusable, and extensible specification that captures the relevant characteristics of entities, which can be used to add semantics to data and information that captures the essential characteristics of an entity in a context-neutral manner. Its primary purpose is to provide standardised terms that can be reused across various application domains, typically realised as a lightweight ontology (optionally accompanied by a permissive data shape) and documented in a concise specification. Core vocabularies for SEMIC were created as part of the https://ec.europa.eu/isa2/home_en/[ISA^2^ program].

== A Practical Example

Imagine you are starting a business in another EU country. To complete the registration, you need to submit a criminal record certificate and a diploma certificate to multiple public organisations. In many countries, this process is still manual—people must physically visit different ministries, request documents, and submit them in person or via email. Each organisation may use different formats and terminology, making it difficult for institutions to interpret and process the information correctly, possibly making mistakes during data entry due to terminological confusion that subsequently have to be corrected. Without a common reference vocabulary, these organizations interpret the data differently, making seamless exchange impossible. +

Now, imagine an alternative scenario, such as indicated by the https://ec.europa.eu/digital-building-blocks/sites/display/OOTS/OOTSHUB+Home[Once-Only Technical System (OOTS)] for the https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32018R1724&from=EN[Single Digital Gateway Regulation], one where this entire process is fully automated. Instead of individuals having to visit multiple offices, the ministries and public administrations would communicate directly with each other, exchanging the necessary information in a structured and consistent manner. The citizen could simply grant approval to the administration office to fetch the data from their home country that already had recorded the relevant data. This would eliminate the need for duplicate document submissions and avoid possible data entry issues, thereby reducing the hassle and costs of mobility. This is also the aim of the . Defining the _what_ is one step; the _how_ to achieve it is another.   +

How can different systems and institutions "talk" to each other effectively at the level of software applications and databases? The challenge is not only technical but also semantic. It is not enough for systems to simply exchange data—they must also be able to interpret the meaning behind the data in a consistent way such that it will not result in errors or so-called 'dirty' (incorrect or incomplete) data. This requires a common language and a  (multilingual) structured vocabulary at both the business process level and the IT systems level. +

This is where *standards to declare the semantics* play a crucial role. By using *core vocabularies,* public administrations can ensure that data and information is structured in a way understood by both humans and machines. Standardised models allow different organisations to recognise and process information without discrepancies, therewith reducing errors and the need for manual intervention. As a result, governments can facilitate seamless data exchange, ensuring that information is accurately shared, interpreted, and processed across systems, leading to more efficient approvals and interactions for businesses, governmental organisations, and citizens.


== Who shall read this Handbook

This handbook is intended for two main audiences: 1) administrative professionals and legal experts, and 2) technical experts and IT professionals. +
Public administrations involve both legal/administrative experts and technical professionals. While they may not always __“__speak the same language__”__, they must* work together* to ensure smooth digital transformation. Semantic interoperability provides the *common foundation* that allows them to bridge their disciplinary differences and find common ground, *enabling effective collaboration* and thereby contributing to improved public services. +
Each intended audience will gain new insights relevant for their respective roles

=== Administrative Professionals & Legal Experts

By reading this handbook, domain experts will

* Understand the role of semantic interoperability at the EU level, which might also be of use at the national, regional, and local level.
*  Gain insight about how structured data and shared vocabularies enhance legal clarity, data exchange, and cross-border cooperation.
* Gain insights into how interoperability supports public services and reduces administrative burdens.
It is expected that this will facilitate coordination with technical teams to ensure that interoperability initiatives meet both legal and operational requirements and assist the administrative professionals and legal experts in making informed decisions about financing and prioritising IT projects that align with interoperability goals.

=== Technical Experts & IT Professionals

By engaging with this handbook as both a reference manual and a practical guide, the technical experts and IT professionals who design, implement, and maintain the software ecosystem will:

* Learn how to design and implement interoperable systems using Core Vocabularies and semantic data models.
* Understand methodologies for creating, mapping, and integrating semantic data models in public administration systems.
* Be able to apply best practices for data exchange, ensuring consistency and accuracy across different systems.
* Use standardised approaches to enhance data accessibility, transparency, and reuse in line with FAIR principles.
* Ensure compliance with Semic style-guide principles. 
It is expected that this will not only facilitate communication with the domain experts, but also further streamline software development conformant to the user specification and, ultimately, the citizens who benefit from more smoothly functioning digital services. 

==  How this Handbook is structured

The *SEMIC Core Vocabularies Handbook* is designed to practically guide public administrations in achieving semantic interoperability. It provides clear guidance on how to use core vocabularies to create semantic data specifications that align with EU initiatives, how to reuse them, and how to implement them. Additionally, it outlines key https://semiceu.github.io/core-vocs-handbook/public-review/use-cases.html#_use_cases:~:text=Unaddressed%20use%20cases-,Use%20cases,-This%20handbook%20serves[use cases] demonstrating practical applications of these vocabularies. +
The Handbook has two types of content:

* *Explanatory Sections*:  Intended for administrative professionals and legal experts. They explain the role of Core Vocabularies, along with relevant use cases and a conceptual framework. It helps non-technical stakeholders understand why semantic interoperability matters and how it supports policy implementation.
* *Practical Guidance Sections*: Designed for technical experts, data architects, and IT professionals, which provide methodologies and step-by-step tutorials for adopting and implementing Core Vocabularies. It includes instructions on creating new semantic data specifications by extending Core Vocabularies, mapping existing data models to them, and ensuring interoperability through standardised practices.

The *structure of the main part of the handbook* is as follows.
First, several principal *use cases* will be introduced, which feature the most common, challenging, and interesting scenarios.
It is augmented with other scenarios to indicate further possible usage.
This is followed by *guidelines for implementation*, which includes procedures for how to create new models and how to map existing ones.
These guidelines are demonstrated in the *tutorials and examples* for the use cases.
Finally, it contains a *glossary of terms* for easy reference.

