== Introduction

[[sec:what-is-interoperability]]
=== What is interoperability?

The term "interoperability" comprising of  ‘inter’ (Latin for between), ‘opera’ (Latin for work), and ‘ability’, refers to the intrinsic nature
of systems or entities working together to achieve shared goals.

Interoperability in the EU context refers to the capacity of systems or organisations, including public administrations,
businesses, and citizens, to collaborate effectively and pursue common objectives across borders. This capability is crucial
for providing efficient digital public services, facilitating economic transactions, and supporting the free movement of goods,
services, people, and data. The European Interoperability Framework (EIF)[xref:references.adoc#ref:1[eif]],
[xref:references.adoc#ref:2[eif2]] and Interoperable Europe Act (IEA) [xref:references.adoc#ref:3[reg24-903]] emphasise that interoperability involves the seamless exchange of information and trusted data sharing across sectors and administrative layers, which is essential for improving policy-making and public service delivery.


[[sec:interoperability-through-semantic-specifications]]
=== Interoperability through semantic specifications

*Semantic interoperability*  ensures that the precise meaning of exchanged data is maintained throughout its transmission, 
adhering to the principle that "what is sent is what is understood", encompassing both the semantic
and syntactic aspects of data. The semantic aspect focuses on the meaning of data elements and their relationships, whereas
the syntactic aspect deals with the structure or format of the data as it is exchanged. On the other hand, *technical interoperability*
covers the infrastructures and applications that facilitate the linkage between systems and services. This includes aspects
such as data representation, transmission methods, API design, access rights management, security, and overall system performance.

Semantic data specifications are detailed, standardised data modelling descriptions
that help manage how data is defined, represented, and communicated across different systems. They comprise various artefacts
that are both machine-readable and human-understandable, thus supporting consistent interpretation and utilisation across
diverse IT environments and stakeholders (e.g. developers, business experts, end users, administrators, etc.).

The SEMIC Style Guide [xref:references.adoc#ref:4[sem-sg]] provides essential guidelines for creating
and managing  such specifications, covering naming conventions, syntax, and the organisation of artefacts into two critical
types of semantic data specifications: Core Vocabularies and Application Profiles.

The Core Vocabularies  are semantic data specifications that enable public
administrations to standardise data exchange processes, thus enhancing the clarity and consistency of data across different
systems and sectors. By leveraging these standards, administrations can effectively bridge the gap between differing data
practices, ensuring seamless service delivery that meets the needs of citizens and businesses alike.

[[sec:what-are-the-core-vocabularies]]
=== What are the Core Vocabularies?
Core Vocabularies are simplified, reusable and extensible data models that capture the fundamental characteristics of a data entity in a context-neutral and syntax-neutral
fashion [xref:references.adoc#ref:5[cv-hb]]. The SEMIC style guide exlains how the  Core Vocabularies [xref:references.adoc#ref:6[sem-sg-cvs]]
are context-neutral semantic building blocks that can be extended into context-specific semantic data specifications to ensure semantic consistency. When the Core Vocabularies are extended
to create domain specifications and information exchange models, additional meaning (semantics) is added to the specifications,
due to the contextualisation.

[[sec:scope]]
// === Scope
// This handbook describes approaches for:
//
// * re-using Core Vocabularies in creating new semantic data specifications or stand-alone data models, and +
// * mapping existing data models to the Core Vocabularies.
//
// The following aspects are NOT included in this handbook:
//
// * a complete methodology for syntax binding and toolset for creating data model specifications, as the Core Vocabularies intend
// to remain syntax neutral.
// * specific methodology recommendations, data model library, or tools. Such choices are heavily dependent on the domain and
// the task at hand.
