=== Create a new JSON-LD context definition

[[sec:uc12-d]]
|===
|{set:cellbgcolor: #a8c6f7}
*Use Case UC1.2: Create a new JSON-LD context definition*

|{set:cellbgcolor: #f5f8fc}
*Goal:* Create a new standalone JSON-LD context definition that uses terms from Core Vocabularies.

|*Primary Actors:* Semantic Engineer, Software Engineer

|*Description:* The goal is to design and create a new JSON-LD context definition that is not part of a more comprehensive semantic data specification, relying on terms from existing CVs as much as possible. As an information exchange data model, a JSON-LD context definition can be integrated in describing data, building APIs, and other operations involved in information exchange.

|*Example:* Core Person Vocabulary [xref:references.adoc#ref:32[cpv-json-ld]], Core Business Vocabulary [xref:references.adoc#ref:33[cbv-json-ld]]

|*Note:* A detailed methodology to be applied for use cases will be provided in the xref:how-to-create-new-data-models.adoc#sec:create-a-new-json-ld-context-definition[Create a new JSON-LD context definition] section.
|===

[[sec:create-a-new-json-ld-context-definition]]
=== Methodology to create a new JSON-LD context definition

This section provides detailed instructions for addressing use case xref:use-cases.adoc#sec:uc12[UC1.2].

JSON-LD combines the simplicity, power, and web ubiquity of JSON with the concepts of Linked Data. Creating JSON-LD context definitions facilitates this synergy. This ensures that when data is shared or integrated across systems, it maintains its meaning and can be understood in the same way across different contexts. Here’s a guide on how to create new JSON-LD contexts for existing CVs, using the Core Person Vocabulary as an example.

. Import or define elements
. Shape structure

==== Import or define elements

When a CV has defined an associated JSON-LD context, it is not only easy, but also advisable to directly import this context using the `@import` keyword. This enables seamless reuse and guarantees that any complex types or elements defined within the vocabulary are integrated correctly and transparently within new schemas.

    "@context": {"@import": "https://json-ld.org/contexts/remote-context.jsonld", }

In cases where the CV does not provide an JSON-LD context, it is necessary to create for the reused URIs the corresponding field element definitions. To start, gather all the terms from the Core Person Vocabulary that you want to include in your JSON-LD context. Terms can include properties like `xref:references.adoc#ref:49[given name]`, `xref:references.adoc#ref:50[family name]`, `xref:references.adoc#ref:51[date of birth]`, and relationships like `xref:references.adoc#ref:52[residency]` or `xref:references.adoc#ref:53[contact point]`.

Then, decide the desired structure of the JSON-LD file, by defining the corresponding keys, for example `Person.givenName`, `Person.familyName`, `Person.dateOfBirth`, `Person.residency`, `Person.contactPoint`. These new fields must adhere to the naming defined by the CV to maintain consistency.

Finally, assign URIs to keys. Each term in your JSON-LD context must be associated with a URI from an ontology that defines its meaning in a globally unambiguous way. Associate the URIs established in CVs to JSON keys using the same CV terms. For example:

    "Person.contactPoint": {"@id": "http://data.europa.eu/m8g/contactPoint"}.

The ones that are imported by the CVs, shall be used as originally defined, for example from FOAF:

    "Person.givenName": {"@id": "http://xmlns.com/foaf/0.1/givenName"}.

==== Shape structure

Start defining the structure of the context by relating class terms with property terms and then, if necessary, property terms with other classes.

Commence by creating a JSON structure that starts with a `@context` field. This field will contain mappings from your vocabulary terms to their respective URIs. Continue by defining fields for Classes and subfields for their properties.

If the JSON-LD context is developed with the aim of being used directly in exchange specific to an application scenario, then aim to establish a complete tree structure that starts with a single root class. To do so, specify precise `@type` references linking to the specific Class. For example:

    "Person.contactPoint" : {"@id": "http://data.europa.eu/m8g/contactPoint", "@type": "ContactPoint"}.

If the aim of the developed JSON-LD context is rather ensuring semantic correspondences, without any structural constraints, which is the case for core or domain semantic data specification, then definitions of structures specific to each entity type and its properties suffice, using only loose references to other objects. For example:

    "Person.contactPoint": {"@id": "http://data.europa.eu/m8g/contactPoint", "@type": "@id"}

[[sec:create-a-json-ld-definition]]
include::creating JSON-LD context (UC 1.2).adoc[creating JSON-LD context (UC 1.2)]

