= Create a new JSON-LD context definition

== Description

Use case 1.2 to create a new JSON-LD context definition is specified as follows.

[[sec:uc12-d]]
|===
|{set:cellbgcolor: #a8c6f7}
*Use Case UC1.2: Create a new JSON-LD context definition*

|{set:cellbgcolor: #f5f8fc}
*Goal:* Create a new standalone JSON-LD context definition that uses terms from Core Vocabularies.

|*Primary Actors:* Semantic Engineer, Software Engineer

|*Description:* The goal is to design and create a new JSON-LD context definition that is not part of a more comprehensive semantic data specification, relying on terms from existing CVs as much as possible. As an information exchange data model, a JSON-LD context definition can be integrated in describing data, building APIs, and other operations involved in information exchange.

|*Example:* Core Person Vocabulary [xref:references.adoc#ref:32[cpv-json-ld]], Core Business Vocabulary [xref:references.adoc#ref:33[cbv-json-ld]]

|*Note:* A detailed methodology to be applied for use cases will be provided in the xref:how-to-create-new-data-models.adoc#sec:create-a-new-json-ld-context-definition[Create a new JSON-LD context definition] section.
|===

[[sec:create-a-new-json-ld-context-definition]]
== Guideline to create a new JSON-LD context definition

This section provides guidelines for addressing use case xref:use-cases.adoc#sec:uc12[UC1.2].

https://www.w3.org/TR/json-ld11/[JSON-LD] is a W3C Recommendation for serialising Linked Data, combining the simplicity, power, and Web ubiquity of JSON with the concepts of Linked Data. Creating JSON-LD context definitions facilitates this synergy. This ensures that when data is shared or integrated across systems, it maintains its meaning and can be understood in the same way across different contexts. This guide describes how to create new JSON-LD contexts for existing Core Vocabularies.

The three key phases are: 

. Import or define elements
. Shape structure
. Review and validate

=== Import or define elements

When a Core Vocabulary has defined an associated JSON-LD context already, it is not only easy, but also advisable to *directly import this context* using the `@import` keyword. This enables seamless reuse and guarantees that any complex types or elements defined within the vocabulary are integrated correctly and transparently within new schemas.

In cases where the Core Vocabulary does not provide an JSON-LD context, it is necessary to *create the corresponding field element definitions* for the reused URIs. To start, gather all the terms from the selected Core Vocabulary that need to be included in the JSON-LD context. 

Then, decide the desired structure of the JSON-LD file, by *defining the corresponding keys*, such as `Person.givenName`. These new fields must adhere to the naming defined by the selected Core Vocabulary to maintain consistency.

Finally, *assign URIs to keys*. Each term in the  JSON-LD context must be associated with a URI from an ontology that defines its meaning in a globally unambiguous way. Associate the URIs established in Core Vocabularies to JSON keys using the same CV terms. 

The ones that are imported by the Core Vocabularies, shall be used as originally defined.

=== Shape structure

==== Main shaping of the structure

Start with defining the structure of the context by *relating class terms with property terms* and then, if necessary, property terms with other classes.

Commence by creating a JSON structure that starts with a `@context` field. This field will contain mappings from one’s own vocabulary terms to other’s respective URIs. Continue by defining fields for Classes and subfields for their properties.

If the JSON-LD context is developed with the aim of being used directly in exchange specific to an application scenario, then aim to establish a complete tree structure that starts with a single root class. To do so, specify precise `@type` references linking to the specific Class. 

If the aim of the developed JSON-LD context is rather ensuring semantic correspondences, without any structural constraints, which is the case for core or domain semantic data specification, then definitions of structures specific to each entity type and its properties suffice, using only loose references to other objects. 

==== Improvements to the structure

To meet wishes from API consumers, one may use *aliasing* of keywords, where a JSON-LD context element is given a more easily recognisable string.

One can also *extend the context* by reusing terms from Core Vocabularies, which also uses the `@import` keyword if included as a whole. Alternatively, single elements can be added, such as additional properties and mapping those to other vocabulary elements of other vocabularies. 


=== Review and validate

First, one should review the created context against any prior requirements that may have been described: is all prospected content indeed included in the context?

Second, the syntax should be verified with a JSON-LD validator, such as https://json-ld.org/playground/[JSON-LD Playground] to ensure that the context is free of errors and all URLs used are operational.



[[sec:create-a-json-ld-definition]]
include::creating JSON-LD context (UC 1.2).adoc[creating JSON-LD context (UC 1.2)]

